### ISSUE TITLE
Crashed At IDEDiagnosticActivityLogMessage 

### ISSUE THREAD

**Issue by BluesJiang** [segiddins/xcactivitylog#3]
Traceback (most recent call last):
        23: from /Users/bluesjiang/Desktop/Creative/tbtools/lib/TBLint/test.rb:22:in `<main>'
        22: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/xcactivitylog.rb:14:in `parse_file'
        21: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/slf0/parser.rb:15:in `parse!'
        20: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/slf0/parser.rb:26:in `parse_tokens!'
        19: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/slf0/token.rb:71:in `object'
        18: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/xcactivitylog/parser.rb:20:in `block in deserializer_for'
        17: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/xcactivitylog/parser.rb:26:in `deserialize_instance_of'
        16: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/xcactivitylog/parser.rb:26:in `each'
        15: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/xcactivitylog/parser.rb:29:in `block in deserialize_instance_of'
        14: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/slf0/token.rb:63:in `object_list'
        13: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/slf0/token.rb:63:in `new'
        12: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/slf0/token.rb:63:in `initialize'
        11: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/slf0/token.rb:64:in `block in object_list'
        10: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/slf0/token.rb:71:in `object'
         9: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/xcactivitylog/parser.rb:20:in `block in deserializer_for'
         8: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/xcactivitylog/parser.rb:26:in `deserialize_instance_of'
         7: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/xcactivitylog/parser.rb:26:in `each'
         6: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/xcactivitylog/parser.rb:29:in `block in deserialize_instance_of'
         5: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/slf0/token.rb:63:in `object_list'
         4: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/slf0/token.rb:63:in `new'
         3: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/slf0/token.rb:63:in `initialize'
         2: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/slf0/token.rb:64:in `block in object_list'
         1: from /Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/slf0/token.rb:71:in `object'
/Users/bluesjiang/.gem/ruby/2.6.0/gems/xcactivitylog-0.2.1/lib/xcactivitylog/parser.rb:16:in `deserializer_for': uninitialized constant XCActivityLog::IDEDiagnosticActivityLogMessage (NameError)
Did you mean?  XCActivityLog::IDEClangDiagnosticActivityLogMessage

**Comment by segiddins** [comment]
Can you please share the activity log that causes the crash? Thanks!
